version: "3.7"
services:
  alice:
    container_name: alice
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - ./hero_db/alice:/data
    image: samelamin/hero:relaychain-demo
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=debug,parachain::provisioner=trace
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  bob:
    container_name: bob
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - ./hero_db/bob:/data
    image: samelamin/hero:relaychain-demo
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=debug,parachain::provisioner=trace
    ulimits: *a1
  hero:
    container_name: hero-1
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - ./hero_db/hero:/hero/data
    image: samelamin/hero:parachain-demo
    command:
      - --base-path=/hero/data
      - --chain=/app/local-2000.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --alice
      - --node-key=94c1a67a21a895a879e19d14ae74b2d874f2609401da2cd3f58b2c10c558ca65
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    ulimits: *a1

