version: "3.7"
services:
  alice:
    container_name: alice
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - ./hero_db/alice:/data
    image: samelamin/hero:relaychain-demo
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --allow-private-ipv4
      - --rpc-methods=unsafe
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=debug,parachain::provisioner=trace
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  bob:
    container_name: bob
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - ./hero_db/bob:/data
    image: samelamin/hero:relaychain-demo
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      -  --allow-private-ipv4
      - --rpc-methods=unsafe
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=debug,parachain::provisioner=trace
    ulimits: *a1
  hero-1:
    container_name: hero-1
    restart: always
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - ./hero_db/hero-1:/hero/data
    image: samelamin/hero:parachain-demo
    command:
      - --base-path=/hero/data
      - --chain=/app/local-2000.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --allow-private-ipv4
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --bob
      - --node-key=94c1a67a21a895a879e19d14ae74b2d874f2609401da2cd3f58b2c10c558ca65
      - --
      - --chain=/app/rococo-local.json
      - --wasm-execution=compiled
      - --execution=wasm
  hero-2:
    container_name: hero-2
    restart: always
    depends_on:
      - "hero-1"
    ports:
      - 9947:9944
      - 9936:9933
      - 30336:30333
    volumes:
      - ./hero_db/hero-2:/hero/data
    image: samelamin/hero:parachain-demo
    command:
      - --base-path=/hero/data
      - --chain=/app/local-2000.json
      - --bootnodes=/ip4/127.0.0.1/tcp/30335/p2p/12D3KooWMrBJVdD4Tq9brTp76bkXeTdkx28CYfRKj9BVjapBSjm2
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --allow-private-ipv4
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --bob
      - --
      - --chain=/app/rococo-local.json
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    ulimits: *a1

